use cricket;
select * from cricket_data;
select * from venue;
select * from month_trend;
select * from team_wickets;
select * from dismissal_type;
select * from batsman_performance;
select * from avearge_st_formate;
SET SQL_SAFE_UPDATES = 0;
select count(*) as TotalMatch from cricket_data;
select count(distinct Batsman_Name)as TheBastmanName from cricket_data;
select Match_ID,Innings,Batsman_Name,Runs_Scored from cricket_data where Runs_Scored>50;
select Batsman_Name,SUM(Runs_Scored) as total_runs from cricket_data group by Batsman_Name order by total_runs desc;
select Venue,SUM(Runs_Scored)as total_runs from cricket_data group by Venue order by total_runs desc limit 5;
select Bowler_Name,SUM(Wickets_Taken) as total_wickets from cricket_data group by Bowler_Name order by total_wickets desc;
select Batsman_Name,(SUM(Fours*4 + Sixes*6) * 100.0 / SUM(Runs_Scored)) as boundary_percentage from cricket_data group by Batsman_Name;
select Batting_Team,avg(Runs_Scored) as avg_team_runs from cricket_data group by Batting_Team order by avg_team_runs desc limit 5;
select Bowler_Name,avg (Runs_Scored / Overs_Numeric) as avg_economy from cricket_data where Overs_Numeric > 0 group by Bowler_Name;
select Venue,avg(Runs_Scored / Balls_Faced) * 6 as avg_run_rate from cricket_data where Balls_Faced > 0 group by Venue;
select Batsman_Name,Bowler_Name,SUM(Runs_Scored) as runs_against_bowler from cricket_data group by Batsman_Name, Bowler_Name order by runs_against_bowler desc;
select Batsman_Name,SUM(Runs_Scored) as total_runs,rank() over (order by SUM(Runs_Scored) desc) as run_rank from cricket_data group by Batsman_Name;
select Match_Date_Clean,Runs_Scored,SUM(Runs_Scored) over (order by Match_Date_clean)as running_total_runs from cricket_data;
select Bowler_Name,SUM(Wickets_Taken) * 100.0 / SUM(SUM(Wickets_Taken)) over () as wicket_percentage from cricket_data group by Bowler_Name;
select Bowler_Name,SUM(Balls_Faced) / NULLIF(SUM(Wickets_Taken),0) as balls_per_wicket,rank() over (order by SUM(Balls_Faced) / NULLIF(SUM(Wickets_Taken),0)) as bowler_rank from cricket_data group by  Bowler_Name;
select *from cricket_data where Strike_Rate_Calc is null or Strike_Rate_Calc <= 0;
select *from cricket_data where Overs_Numeric <= 0 or Overs_Numeric > 20;
select *from cricket_data where Wickets_Taken > 5;
select *from cricket_data where Match_Date_Clean is null or Match_Date_Clean = '';
